# То же самое, что и в серверном Dockerfile.

FROM python:latest

# Импортируем 'client.py' в папку '/client/'.

ADD client.py /client/
ADD requirements.txt /client/

# Устанавливаем в качестве рабочей директории '/client/'.

WORKDIR /client/

# устанавливаем требуемые зависимости

# RUN pip install -r /client/requirements.txt
